name: CI

on:
  push:
    branches:
      - main

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Dependencies
        run: |
          pip install mlflow

      - name: Run MLflow Project
        run: |
          mlflow run MLProject --env-manager=local
      - name: Save mlruns
        run: |
          git config --global user.name "${{ secrets.username }}"
          git config --global user.email "${{ secrets.email }}"

          git add .

          git commit -m "Save mlruns" || true

          git push
